# ===========================
# DEV PROFILE OVERRIDES
# ===========================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# More verbose logging for development
logging.level.com.timetablingapp=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
